// @ts-check

/**
 * Auto-generated sidebar based on the docs/ folder structure.
 * Adding a new article (Markdown file) to any docs/<category>/ folder
 * will automatically extend both the left sidebar and the top navbar
 * (the navbar is regenerated on `npm start` / `npm run build`).
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guideSidebar: [
    {type: 'autogenerated', dirName: '.'},
  ],
};

export default sidebars;
