// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guideSidebar: [
    'guide',
    {
      type: 'category',
      label: '国外银行',
      collapsed: true,
      link: {type: 'generated-index', title: '国外银行'},
      items: [
        'foreign-banks/overview',
        {
          type: 'category',
          label: '申请攻略',
          collapsed: true,
          link: {type: 'generated-index', title: '国外银行申请攻略'},
          items: [{type: 'autogenerated', dirName: 'foreign-banks/application-guides'}],
        },
      ],
    },
    {
      type: 'category',
      label: '国外券商',
      collapsed: true,
      link: {type: 'generated-index', title: '国外券商'},
      items: [
        'foreign-brokers/overview',
        {
          type: 'category',
          label: '申请攻略',
          collapsed: true,
          link: {type: 'generated-index', title: '国外券商申请攻略'},
          items: [{type: 'autogenerated', dirName: 'foreign-brokers/application-guides'}],
        },
        {
          type: 'category',
          label: '申请策略',
          collapsed: true,
          link: {type: 'generated-index', title: '国外券商申请策略'},
          items: [{type: 'autogenerated', dirName: 'foreign-brokers/strategy-guides'}],
        },
      ],
    },
    {
      type: 'category',
      label: '加密 Web3',
      collapsed: true,
      link: {type: 'generated-index', title: '加密 Web3'},
      items: [
        'crypto-web3/overview',
        {
          type: 'category',
          label: '平台攻略',
          collapsed: true,
          link: {type: 'generated-index', title: '加密 Web3 平台攻略'},
          items: [{type: 'autogenerated', dirName: 'crypto-web3/platform-guides'}],
        },
        {
          type: 'category',
          label: '申请策略',
          collapsed: true,
          link: {type: 'generated-index', title: '加密 Web3 申请策略'},
          items: [{type: 'autogenerated', dirName: 'crypto-web3/strategy-guides'}],
        },
      ],
    },
    {
      type: 'category',
      label: '跨境出海',
      collapsed: true,
      link: {type: 'generated-index', title: '跨境出海'},
      items: [
        'cross-border/overview',
        {
          type: 'category',
          label: '落地攻略',
          collapsed: true,
          link: {type: 'generated-index', title: '跨境出海落地攻略'},
          items: [{type: 'autogenerated', dirName: 'cross-border/playbooks'}],
        },
        {
          type: 'category',
          label: '申请策略',
          collapsed: true,
          link: {type: 'generated-index', title: '跨境出海申请策略'},
          items: [{type: 'autogenerated', dirName: 'cross-border/strategy-guides'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'AI 时代',
      collapsed: true,
      link: {type: 'generated-index', title: 'AI 时代'},
      items: [
        'ai-era/overview',
        {
          type: 'category',
          label: '工具攻略',
          collapsed: true,
          link: {type: 'generated-index', title: 'AI 工具攻略'},
          items: [{type: 'autogenerated', dirName: 'ai-era/tool-guides'}],
        },
        {
          type: 'category',
          label: '申请策略',
          collapsed: true,
          link: {type: 'generated-index', title: 'AI 时代申请策略'},
          items: [{type: 'autogenerated', dirName: 'ai-era/strategy-guides'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'AI 美女相册',
      collapsed: true,
      link: {type: 'generated-index', title: 'AI 美女相册'},
      items: [
        'ai-gallery/overview',
        {
          type: 'category',
          label: '创作PROMPT',
          collapsed: true,
          link: {type: 'generated-index', title: 'AI 美女相册创作PROMPT'},
          items: [{type: 'autogenerated', dirName: 'ai-gallery/creative-guides'}],
        },
      ],
    },
    {
      type: 'category',
      label: '写作模板',
      collapsed: true,
      link: {type: 'generated-index', title: '写作模板'},
      items: [{type: 'autogenerated', dirName: 'templates'}],
    },
  ],
};

export default sidebars;
